# Generated by Django 3.0.10 on 2020-10-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=40)),
                ('flight_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fly_duration', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('booking_token', models.TextField()),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_from', to='flights.Airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_to', to='flights.Airport')),
            ],
        ),
    ]
