# Generated by Django 3.0.10 on 2020-10-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='fly_from',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='fly_to',
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_from', to='flights.Airport')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_to', to='flights.Airport')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='direction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='flights.Direction'),
            preserve_default=False,
        ),
    ]
