# Generated by Django 3.0.10 on 2020-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20201021_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(max_length=100),
        ),
    ]
