# Generated by Django 3.0.10 on 2020-10-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20201022_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
